server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password:
  jpa:
    database: MySQL
    hibernate.ddl-auto: update
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: durateodora11@gmail.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    protocol: smtp
    test-connection: false

properties:
  registration-token-size: 20
  authentification-token-size: 20

